// <auto-generated />
using System;
using CaseFile.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseFile.Api.Migrations
{
    [DbContext(typeof(CaseFileDbContext))]
    [Migration("20260821143359_AddAccusedSuspectIdToPlayerProgress")]
    partial class AddAccusedSuspectIdToPlayerProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseFile.Api.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IntroText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("KillerSuspectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("KillerSuspectId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Clue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuzzleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("StarterCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EvidenceId");

                    b.ToTable("Clues");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkedSuspectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReinterpretedAfterClueId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReinterpretedDescription")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("LinkedSuspectId");

                    b.HasIndex("ReinterpretedAfterClueId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectiveName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("CaseFile.Api.Models.PlayerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AccusedCorrectly")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AccusedSuspectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentClueIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerSessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SolvedClueIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CaseId", "PlayerSessionId")
                        .IsUnique();

                    b.ToTable("PlayerProgress");
                });

            modelBuilder.Entity("CaseFile.Api.Models.PuzzleTestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClueId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClueId");

                    b.ToTable("PuzzleTestCases");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlibiText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsKiller")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Case", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Suspect", "KillerSuspect")
                        .WithMany()
                        .HasForeignKey("KillerSuspectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KillerSuspect");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Clue", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Case", "Case")
                        .WithMany("Clues")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseFile.Api.Models.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Evidence", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Case", "Case")
                        .WithMany("Evidence")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseFile.Api.Models.Suspect", "LinkedSuspect")
                        .WithMany("LinkedEvidence")
                        .HasForeignKey("LinkedSuspectId");

                    b.HasOne("CaseFile.Api.Models.Clue", "ReinterpretedAfterClue")
                        .WithMany()
                        .HasForeignKey("ReinterpretedAfterClueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("LinkedSuspect");

                    b.Navigation("ReinterpretedAfterClue");
                });

            modelBuilder.Entity("CaseFile.Api.Models.PlayerProgress", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseFile.Api.Models.Player", null)
                        .WithMany("ProgressRecords")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("CaseFile.Api.Models.PuzzleTestCase", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Clue", "Clue")
                        .WithMany("TestCases")
                        .HasForeignKey("ClueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clue");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Suspect", b =>
                {
                    b.HasOne("CaseFile.Api.Models.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Case", b =>
                {
                    b.Navigation("Clues");

                    b.Navigation("Evidence");

                    b.Navigation("Suspects");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Clue", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Player", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("CaseFile.Api.Models.Suspect", b =>
                {
                    b.Navigation("LinkedEvidence");
                });
#pragma warning restore 612, 618
        }
    }
}
